### ISSUE TITLE
report 생성하는 과정에서 에러 나네요..

### ISSUE THREAD

**Issue by bhtak** [smqd/smqd-plugin-rptsvr#2]
소스를 보면, scala match가 안되는 경우가 있는 것 같은데, 확인 바랍니다. 

```
2019-07-03 10:45:55,244 [d%20status%20=%20'Q']  DEBUG c.u.c.m.m.invoice.ReportRouteBuilder - qrcode_path=/nas1/rpt/inbox/invoice-6748-mn-bohuntak@gmail.com.png file.exists=true file.size=20354 data.size=20354 link=http://qpay.mn/q/?q=k6C2FK6XAb8Tjqqftl5kZeFSkFi8DW
2019-07-03 10:45:56,055 [d%20status%20=%20'A']  DEBUG c.t.rptsvr.repo.db.DBRepository - getResource uri=/public/Invoice/email_body/mn, isReferenced=false
2019-07-03 10:45:56,156 [d%20status%20=%20'A']  ERROR o.a.c.processor.DefaultErrorHandler - Failed delivery for (MessageId: ID-ocs1a-1562119463547-0-89626 on ExchangeId: ID-ocs1a-1562119463547-0-89625). Exhausted after delivery attempt: 1 caught: scala.MatchError: Some(net.sf.jasperreports.engine.JasperReport@26a23f4d) (of class scala.Some)

Message History
---------------------------------------------------------------------------------------------------------------------------------------
RouteId              ProcessorId          Processor                                                                        Elapsed (ms)
[rptTrigger        ] [rptTrigger        ] [sql://select%20email_seq,%20report_src,%20report_key1,%20report_val1,%20report] [       101]
[rptTrigger        ] [process37         ] [Processor@0x6a65851a                                                          ] [        98]

Stacktrace
---------------------------------------------------------------------------------------------------------------------------------------
scala.MatchError: Some(net.sf.jasperreports.engine.JasperReport@26a23f4d) (of class scala.Some)
	at com.thing2x.rptsvr.engine.LruCache.fromFuture(LruCache.scala:37)
	at com.thing2x.rptsvr.engine.ReportEngine.$anonfun$loadReportUnit$1(ReportEngine.scala:144)
	at scala.util.Success.$anonfun$map$1(Try.scala:255)
	at scala.util.Success.map(Try.scala:213)
	at scala.concurrent.Future.$anonfun$map$1(Future.scala:292)
	at scala.concurrent.impl.Promise.liftedTree1$1(Promise.scala:33)
	at scala.concurrent.impl.Promise.$anonfun$transform$1(Promise.scala:33)
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:64)
	at akka.dispatch.BatchingExecutor$AbstractBatch.processBatch(BatchingExecutor.scala:55)
	at akka.dispatch.BatchingExecutor$BlockableBatch.$anonfun$run$1(BatchingExecutor.scala:91)
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:23)
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:85)
	at akka.dispatch.BatchingExecutor$BlockableBatch.run(BatchingExecutor.scala:91)
	at akka.dispatch.TaskInvocation.run(AbstractDispatcher.scala:40)
	at akka.dispatch.ForkJoinExecutorConfigurator$AkkaForkJoinTask.exec(ForkJoinExecutorConfigurator.scala:44)
	at akka.dispatch.forkjoin.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at akka.dispatch.forkjoin.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1339)
	at akka.dispatch.forkjoin.ForkJoinPool.runWorker(ForkJoinPool.java:1979)
	at akka.dispatch.forkjoin.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:107)
```

**Comment by OutOfBedlam** [comment]
fix is included in v0.1.1
